import Home from "../Pages/Home";
import Login from "../Pages/Login";
import Admin from "../Pages/Admin/Admin";
import Book from "../Pages/Admin/Book";
import AddBook from "../Pages/Admin/Book/Add";
import Genre from "../Pages/Admin/Genre";
import AddGenre from "../Pages/Admin/Genre/Add";
import UpdateBook from "../Pages/Admin/Book/Update";
import User from "../Pages/Admin/User";
import UpdateUser from "../Pages/Admin/User/Update";
import AddAdmin from "../Pages/Admin/AdminUsers/Add";
import Logout from "../Pages/Logout";
import AdminUsers from "../Pages/Admin/AdminUsers";
import Register from "../Pages/Register";
import BookDetails from "../Pages/Admin/Book/BookDetails";
import Genres from "../Pages/Admin/Genre/Genres";
import BooksByGenre from "../Pages/Admin/Genre/BooksByGenre";
import UserProfile from "../Pages/Admin/UserProfile";
import ChangePassword from "../Pages/ChangePassword";
import Cart from "../Pages/Admin/Cart";

const protectedRoutes = [
  {path: '/dashboard', component: <Home/>},
  {path: '/settings', component: <Home/>},
  {path: '/Admin', component: <Admin/>},
  {path: '/book', component: <Book/>},
  {path: '/book/add', component: <AddBook/>},
  {path: '/book/update/:id', component: <UpdateBook/>},
  {path: '/genre', component: <Genre/>},
  {path: '/genre/add', component: <AddGenre/>},
  {path: '/user', component: <User/>},
  {path: '/user/update/:id', component: <UpdateUser/>},
  {path: '/admin/view', component: <AdminUsers/>},
  {path: '/admin/add', component: <AddAdmin/>},
  {path: '/admin/update/:id', component: <UpdateUser/>},
  {path: '/logout', component: <Logout/>},
  {path: '/profile', component: <UserProfile/>},
  {path: '/changepass', component: <ChangePassword/>},
];
const publicRoutes = [
  {path: '/', component: <Home/>},
  {path: '/login', component: <Login/>},
  {path: '/register', component: <Register/>},
  {path: '/book/:id', component: <BookDetails/>},
  {path: '/genres', component: <Genres/>},
  {path: '/genres/:genre', component: <BooksByGenre/>},
  {path: '/cart', component: <Cart/>},
]
export {protectedRoutes, publicRoutes}
